### ISSUE TITLE
Problems When Using with WKWebView

### ISSUE THREAD

**Issue by lylepratt** [markmarijnissen/cordova-app-loader#10]
I'm trying to use the Telerik WKWebView plugin with this. The problem is that the `Origin` header seems to be set to `null` for all XHR requests. This is especially problematic when trying to load files from Amazon S3. Even when their CORS settings are set to allow from `*`, it will not accept `null`. Any advice?

**Comment by micky2be** [comment]
Still having issue loading local file it seems.
Can't manage to download and load new files.

**Comment by braco** [comment]
Anybody solve this?

Getting "WARN: Unhandled rejection filetransfer@http://localhost:12344/bootstrap.js:..." under WK

**Comment by micky2be** [comment]
File is not where WKWebView think it is. 
This is an unresolved problem. 

I might tackle this down once I finish my version of the loader.

**Comment by braco** [comment]
@micky2be: for me, that error was not being able to find the cordova file plugins. Tracked that down with bluebird and extended stack traces. Now it just crashes, though. What are you working on?

**Comment by micky2be** [comment]
A loader which is just an empty shell. No need manifest on the bundle.
+ rollback ability.

For your problem, could you share your manifest please.

**Comment by ObjectiveTruth** [comment]
Closing the issue since it hasn't been updated in 3 months and it appears the was a resolution. If there's more to add to the discussion please reopen :ok_hand:

**Comment by salamalejkum** [comment]
Have you been able to make it work with WKWebView? I've tried without success.

**Comment by clauderic** [comment]
Not sure why this was closed, as far as I can tell there is no resolution... anybody solve this?
