### ISSUE TITLE
Auto-reset when updating apk

### ISSUE THREAD

**Issue by SystemParadox** [markmarijnissen/cordova-app-loader#103]
At the moment, if I update over the air using the loader, and then later update by installing a new APK, it still uses the version from the FileCache, even if the APK is actually a newer version.

I find this a bit confusing, and sometimes wonder why my app isn't updating until I eventually work out that it's using the FileCache version and that I need to reset it to use the APK instead.

Has anyone else come up with a good solution to this?

It's a bit tricky since the manifest uses checksums rather than incrementing version numbers. The best solution I can think of at the moment is to add an `apkVersion.js` file which is excluded from the manifest (so it will only update if the apk is updated). The version set in this file can then be compared against a similar "manifestVersion" which does update with the loader. Then simply:

```
if (apkVersion >= manifestVersion) {
    loader.reset();
}
```

Any thoughts?

**Comment by markmarijnissen** [comment]
That sounds like a good solution.

My original design idea was to have a single authoritive source of truth:
The online version. When dealing with multiple sources of truth (i.e. both
server and APK), things get complicated and you need to use versioning to
keep track of everything.

Is there any reason why you have updated the APK and NOT the online version?

**Comment by SystemParadox** [comment]
It's a semi-offline app. The device is only connected to the network via an ethernet docking cradle.

Since I'm not auto-updating, it's a bit confusing to update the APK and nothing happens. Actually, it's mainly confusing because sometimes updating the APK does update, but only if there have been no over-the-wire updates.

I will implement the solution above. Thanks for the input :)
