### ISSUE TITLE
Calling download() never finishes.

### ISSUE THREAD

**Issue by tkoop** [markmarijnissen/cordova-app-loader#107]
I can call check(), and it returns the correct value of true or false, depending on the manifest.json.  But then when I call download(successFunction, errorFunction), neither successFunction nor errorFunction ever get called. It just does nothing as far as I can tell.

There must be an error somewhere to keep it from returning, but I have no idea what it might be.

Please help.

**Comment by dashkaLimashka** [comment]
In my project download function returns promise. That's mean that I should write  loader.download().then(successFunction, errorFunction). May be it will work for you too.

**Comment by tkoop** [comment]
Thanks.  I just checked my code, and I am indeed calling the "then()" function exactly like you suggest.  It's still not working.

**Comment by tkoop** [comment]
I think I figured out the issue.  I think I wasn't including CordovaPromiseFS.js so the promise from that library never returned.  I just made sure I was including CordovaPromiseFS.js, bluebird.js, and CordovaAppLoader.js correctly.  It's working now.  At least this part is.
