### ISSUE TITLE
Question: Does this way of auto-updating go against the guidelines of Apple?

### ISSUE THREAD

**Issue by doitonlinemedia** [markmarijnissen/cordova-app-loader#119]
I've read somewhere that download files and storing them in cache is against the guidelines from Apple.

Can someone confirm if this is true or not?

Ref:
https://groups.google.com/d/msg/phonegap/LXXeItwopPU/R6vSHtkbF6gJ

**Comment by tmarkovski** [comment]
Not entirely true. Downloading files and loading your app from that is allowed as long as the downloaded code doesn't change what your app was intended to do when it was initially approved.

**Comment by rionord** [comment]
That is my understanding too.

**Comment by doitonlinemedia** [comment]
Thanks for the information!
