### ISSUE TITLE
app.js file inside www is not updated with latest code

### ISSUE THREAD

**Issue by bandhavya** [markmarijnissen/cordova-app-loader#124]
on update, Manifest.root is updated with the file://data/user/0/../files/files/app but files inside the index.html are not reloaded with the latest app.js ?
latest app.js file is in local file system but not updated with app.js that is pointed in index.html
Do we need to explicitly do that reload the app.js file to latest ?

**Comment by betorobson** [comment]
I do strongly recommend not update the whole app. It will be more effective and easy to control when updating just some modules inside the app. For example, having a APP with side menu, home and details whould be smart having this sections split in files like menu.js, home.js and details.js. So, you can easily update just one of them. Leave the app.js just to put togheter these modules.

**Comment by bandhavya** [comment]
Ok. 
My scenario is:
I have a file app.js parallel to index.html. app.js is pointed in index.html as the local file.
I'm updating the app.js file in the server. Now on loader.download(), app.js file is downloaded and it is stored in file://user/0/../files/files/app/app.js
but the local app.js file mentioned in index.html is not updated with the latest code

**Comment by betorobson** [comment]
Could you share your index.html or at least part of <script src> ?

**Comment by bandhavya** [comment]
It works as expected.
Thanks
