### ISSUE TITLE
First load / no connectivity?

### ISSUE THREAD

**Issue by japostoles** [markmarijnissen/cordova-app-loader#14]
If the local files provide an offline experience, and the app is first opened without connectivity, the app fails to load.

This seems to be because the app checks for a manifest in localStorage, and if it doesn't find one, it calls out to the web.  It seems that it never uses the bundled manifest -- is this accurate?  I think it should use the bundled Manifest to boot before calling out if it doesn't exist in localStorage.

**Comment by markmarijnissen** [comment]
No, this is not accurate. Bootstrap.js first checks localstorage, then the bundled manifest. You can see this behavior in the demo app. I expect the error is in your update logic, or the bootstrap script tag points to a incorrect   Manifest location.

—
