### ISSUE TITLE
Need a Way to fix "Endless Update Loop"

### ISSUE THREAD

**Issue by lylepratt** [markmarijnissen/cordova-app-loader#18]
You prevent the loader from downloading an update if the files from the last update match the files from a new update with this message here:
https://github.com/markmarijnissen/cordova-app-loader/blob/5a8959db3ab3ae40ae301447b7599d497a4220e4/index.js#L103

I think the check needs to be something different because in its current form there is no way to CORRECT a previous botched update. It just always ignores subsequent updates with this in place. Ideas?

**Comment by markmarijnissen** [comment]
I am assuming that at least one files has to be changed for an update to be corrected.

However, if you had other issues, this assumption does not hold. Example:
* You had a redirect that caused all files to be `index.html`
* For some reason, the files were missing or corrupt after downloaden.

A solution would be to manually change the file version for this change (for at least one file). Or you could just change some version string in your source code and rebuild your app (thus also creating a new filename version).

Also, when you call `loader.clear()` or `loader.reset()`, the update will be attempted again. (But: all cached files are also deleted!). To prevent a never-ending loop, you should never call `reset()` automatically. Only after a user interaction. (i.e. when user confirms to retry update).

**Comment by lylepratt** [comment]
I did change a file and thus the version hash of one of my source files, but it still would not update.

**Comment by markmarijnissen** [comment]
Interesting. This might be a bug, then! I'll investigate when I have the time. You could help if I can reproduce the issue with the demo app. 

Are you sure the hash changed of the file?

**Comment by markmarijnissen** [comment]
Did I fix it? See https://github.com/markmarijnissen/cordova-app-loader/commit/80ab34170c2126c9e3053c62a8d6ea750aa1a1eb.

Can you check the logic there?
