### ISSUE TITLE
Questions on App Store Update Process when Native Plugins Change

### ISSUE THREAD

**Issue by lylepratt** [markmarijnissen/cordova-app-loader#19]
Hi!

I'm having trouble figuring out the best way to handle changes updates that require Native Plugin additions/changes.

Imaging this scenario:

- Publish app update that has a new Cordova native plugin
- Since remote manifest is THE source for info, we need to also push a Hot Code Update

The problem is that if you have not received the native update yet, the Hot Code Update will be buggy since its referencing native plugins that don't exist.

If you instead wait to issue the hot code update until AFTER your app is approved, you still have no way of knowing whether everyone has updated or not. How can you ever reliably release updates to code depending on native plugins?

**Comment by rajatrocks** [comment]
I would expect that you'd have to have code in your app that looks for the existence of the native plugin, and then acts accordingly, to handle both scenarios. Don't see any way around it.

**Comment by markmarijnissen** [comment]
@rajatrocks Yes, I agree.

Let's reason about this: It's a fact that you cannot force users to do a native update. So you will **never** have a guarantee that the native plugins are up to date.

1. Add a build number in your index.html, so you can track the (native) build of your app.
2. If you want, collect statistics about which native version the user is running. Although you cannot have a guarantee, at least you have knowledge about which versions are running.
3. Every unsafe update (i.e. using native plugins), has to be safe. Which means: optional.
      * If the feature is critical/blocking, you can block the entire app: "Please update your app in the App Store"
      * If the feature is optional, you have to disable it or provide an alternative without the native plugin.

**Comment by ObjectiveTruth** [comment]
Closing this issue since the answer seems to have been answered and there's no more activity. If you have any more issues please reopen the issue :ok_hand:
