### ISSUE TITLE
Always updates on first run after install

### ISSUE THREAD

**Issue by epegzz** [markmarijnissen/cordova-app-loader#20]
The first time I am launching my app it will start normally. Then autoupdate.js (CordovaAppLoader) will do a check and decide that it's time to update, even though the remote manifest.json equals the shipped manifest.json. This results in a reload of the app right some seconds after the app was launched initially.

Is this default behaviour? Or should CordovaAppLoader be smart enough to figure out that no files have changed even on the first time the app starts after being freshly installed?

Also, I'm not sure why the `locarRoot` param is set to `'app'`:
https://github.com/markmarijnissen/cordova-app-loader/blob/master/www/autoupdate.js#L28
Maybe it's related to that, that CordovaAppLoader is expecting the shipped files in an `app` subdirectory but because i have all files directly in the `cordova/www` directory it's not finding them?

Anyway, changing it to `localRoot: ''` did not change anything.

**Comment by epegzz** [comment]
For some reason now everything works fine, yay :)

I'm still curious what the `localRoot` param does though and why it's set to `app` in your sample implementation?

**Comment by markmarijnissen** [comment]
Good to hear!

`localRoot` is the local root folder of the cache. You can use this to store the app in a sub-directory of your storage system. It defaults to `cache`. Is this explanation clear?
