### ISSUE TITLE
Calling Promise.resolve() in AppLoader.prototype.download

### ISSUE THREAD

**Issue by pheinicke** [markmarijnissen/cordova-app-loader#23]
Hi!

My app crashes with "undefined is not a function" when using cordova-app-loader 0.14 and angular $q (using angular 1.3.14).

![promise-resolve](https://cloud.githubusercontent.com/assets/7060709/6487337/e4197cd8-c290-11e4-8d4e-277d1876fbdb.png)

According to https://github.com/markmarijnissen/cordova-app-loader/issues/3#issuecomment-63870204 you already fixed most of these.

Thanks,
Peter

**Comment by markmarijnissen** [comment]
I've fixed this in next release (0.15)
