### ISSUE TITLE
Unable to build project

### ISSUE THREAD

**Issue by pheinicke** [markmarijnissen/cordova-app-loader#25]
Hi,

I tried to create a pull request for a small fix a wrote, but I was not able to build the project.

What I did:
* clone the project
* *sudo npm install webpack -g*
* *npm run-script prepublish*

Got the this error:
> $>npm run-script prepublish

> > cordova-app-loader@0.14.0 prepublish /home/peter/workspace/cordova-app-loader
> > npm run copy-tests && npm run autoupdate && npm run bootstrap && npm run cordova-promise-fs && npm run cordova-app-loader && npm run copy-to-dist && npm run bundle && npm run minify-dist

> > cordova-app-loader@0.14.0 copy-tests /home/peter/workspace/cordova-app-loader
> > cp pegasus.js www/test/pegasus.js && cp node_modules/cordova-promise-fs/test/tests.js www/test/cordova-promise-fs-tests.js && cp node_modules/cordova-file-cache/test/tests.js www/test/cordova-file-cache-tests.js

> cp: der Aufruf von stat für »node_modules/cordova-promise-fs/test/tests.js“ ist nicht möglich: Datei oder Verzeichnis nicht gefunden
> npm ERR! weird error 1
> npm ERR! not ok code 0
> npm ERR! weird error 1
> npm ERR! not ok code 0

which would be "File not found". The whole folder node-modules/cordova-promise-fs/ is missing. *npm install* has the same error. Any suggestions?

Thanks,
Peter

**Comment by markmarijnissen** [comment]
I'm guessing I have a unpublished version of `cordova-promise-fs` on my file system. Should be fixed with next release.

**Comment by pheinicke** [comment]
Still not working in 0.17.
