### ISSUE TITLE
Problem with cache and fonts

### ISSUE THREAD

**Issue by DayBr3ak** [markmarijnissen/cordova-app-loader#31]
When my app gets updated, the loading of some files fail (works if I never update my app).

Here is the error I get :

    (404) GET cdvfile://localhost/persistent/app/lib/ionic/fonts/ionicons.ttf?v=2.0.1 

I'm developing on Android, with crosswalk.
Could you help me ?

edit: before the update by the app loader, it checks for 

    file:///android_asset/www/lib/ionic/fonts/ionicons.ttf?v=2.0.1

**Comment by markmarijnissen** [comment]
Did you add all files included in your CSS in the manifest?



—

**Comment by DayBr3ak** [comment]
As I did not need to reload fonts, no I didn't. I'll try to add those fonts and let you know

**Comment by DayBr3ak** [comment]
It resolved the issue, thank you for your help
