### ISSUE TITLE
npm install fails due to cordova-promise-fs missing from node_modules

### ISSUE THREAD

**Issue by arieljake** [markmarijnissen/cordova-app-loader#35]
this line fails in the npm install process:

````
cp node_modules/cordova-promise-fs/test/tests.js www/test/cordova-promise-fs-tests.js
````

is cordova-promise-fs missing as a dependency in package.json?

**Comment by arieljake** [comment]
This error is fixed by adding cordova-promise-fs to the dependencies list in package.json

**Comment by markmarijnissen** [comment]
Thanks. Will update soon.

**Comment by arieljake** [comment]
touch

**Comment by ObjectiveTruth** [comment]
Closing issue since there appears to be an adequate resolution, if there is new information please reopen
