### ISSUE TITLE
New manifest available, but an earlier update attempt failed. Will not download.

### ISSUE THREAD

**Issue by DayBr3ak** [markmarijnissen/cordova-app-loader#41]
Can this be more specific ? I have no idea where my manifest would be "corrupt". 

    {
      "files": {
        "loader": {
          "version": "e1b6e5505edd086e5a2d2e8f1d38612709e2881a",
          "filename": "dist/loader.js"
        },
        "css": {
          "version": "4163a1616d78cd37b97eb425bafe38efd7de8a96",
          "filename": "dist/ionic.app.css"
        },
        "libs": {
          "version": "4bfc76c49ff7186168f77558a704181b610f91ce",
          "filename": "dist/libs.js"
        },
        "app": {
          "filename": "dist/app.js",
          "version": "f941587acc09bb85857adccac5ee95a774a5ab3b"
        },
        "font_ttf": {
          "filename": "lib/ionic/fonts/ionicons.ttf",
          "version": "6ea051e1975142acc1c87b5e16a9c48520e44731"
        },
        "font_woff": {
          "filename": "lib/ionic/fonts/ionicons.woff",
          "version": "3c2e00d86ce8a574abd47e7f28871b268220418f"
        },
        "font_svg": {
          "filename": "lib/ionic/fonts/ionicons.svg",
          "version": "3f1ca28fcb042d2bcc6ee6a4e3dd817e5132eeea"
        },
        "font_eot": {
          "filename": "lib/ionic/fonts/ionicons.eot",
          "version": "a5653d053229493afd83a863a50a180ced87f6c5"
        }
      },
      "load": [
        "dist/ionic.app.css",
        "dist/loader.js",
        "dist/libs.js",
        "dist/app.js"
      ],
      "version": "74207d570d861b205c2d45e83f0a0589e56bcabf"
    }

Should the files on my server all be in the root folder, or should they have the same path as in my application ?

**Comment by markmarijnissen** [comment]
The error occurs when:

1. First, you perform `check()` and `download()`. This deletes the outdated files from the cache. It writes `newManifest.files` to localStorage.
2. Restart app (or create a new AppLoader)
3. `check()` again: 
      * If the new Manifest files did **NOT** change between step 1 and 3.
      * AND the new Manifest files are **NOT** in the current Manifest.
      * Then the update must have failed. 

For some reason, the files you downloaded in step 1 did **NOT** end up in the current Manifest! The download has failed, or was aborted, or the app was killed,... something prevented from successfully completing all downloads and calling `update()` and yet the app has restarted.

Troubleshooting:

* Check your file permissions (`755`). 
* Are all files available? Check if the links work.
* Did you call `update()` before reloading page?
* Use XCode/Eclipse/Chrome to debug the download and check for errors.

Do you have a better error description? (Perhaps reference this issue :) )

**Comment by arieljake** [comment]
Maybe we should change this. If the download failed due to an Internet service interruption, we don't want to put the loader in a state where it won't try again, do we?

**Comment by ExecutorBG** [comment]
I had a similar issue, it was caused because I had included the bootstrap code before including the cordova.js, thus a check for RequestFileSystem would fail and get the error you did.

So make sure you include the
        <script type="text/javascript" src="cordova.js"></script>

before 
        <script
                type="text/javascript"
                timeout = "5100"
                server = "http://your_server_address/"
                manifest = "manifest.json"
                src="bootstrap.js"></script>

**Comment by DayBr3ak** [comment]
Thank you for your help, but I have included cordova.js included before anything else. And also for Mark, I'm using `autoupdate.js` so I didn't use any of those functions, as for the errors/warnings I get with Chrome debugging tools on my Android, I only get the one this issue is named after. All my files are available, everything should work, except for this mysterious warning.
I'll try to do some `update()` manually, but really this warning makes no sense to me.

**Comment by betorobson** [comment]
Hi markmarijnissen, I hope that you can help with this issue.

I have the same issue, on iOS it is working fine but on Android I got this message: 
New manifest available, but an earlier update attempt failed. Will not download.

In order to understand if I'm doing something wrong, I did an isolated test, which means a single app loading a javascript with a incremental message. After each change in this file, I run that node module to regenerate the manifest.json. The javascript file which is change is called update.js

I will put my files source bellow:

index.html
```
<!DOCTYPE HTML>
<html>
    <head>
        <title>Cordova App Loader</title>

        <!-- Enable all requests, inline styles, and eval() -->
        <meta http-equiv="Content-Security-Policy" content="default-src *; style-src * 'unsafe-inline'; script-src * 'unsafe-inline' 'unsafe-eval'">

        <meta name="viewport" content="width=device-width, maximum-scale=1, user-scalable=no" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black" />

        <script type="text/javascript" src="cordova.js"></script>

        <script type="text/javascript" 
            timeout="5100" 
            server="http://192.168.1.104/cordovaAppLoader/"
            manifest="manifest.json" 
            src="bootstrap.js"></script>
    </head>
    <body>
        <div class="debug" style="padding:30px;"></div>
    </body>
</html>
```
app.js
```
var app = {

    initialize: function() {
        this.bindEvents();
    },

    bindEvents: function() {
        document.addEventListener('deviceready', this.onDeviceReady, false);
        document.addEventListener('resume', this.onResume, false);
    },

    onDeviceReady: function() {
        app.receivedEvent('deviceready');
    },

    onResume: function() {
        console.log('app resumed');
    },

    receivedEvent: function(id) {
        console.log('app received event ' + id);
    }

};

app.initialize();
window.BOOTSTRAP_OK = true;
```
manifest.json
```
{
  "files": {
    "cordova-app-loader-complete": {
      "version": "726b6e72c37e053b022adda6a7aa273d4ef24f2f",
      "filename": "cordova-app-loader-complete.js"
    },
    "autoupdate": {
      "version": "88c7692e829eec77886ea47c1a97f92fc82623b3",
      "filename": "autoupdate.js"
    },
    "app": {
      "version": "e30f2e20be89d3f3e5d8cd98ccf816752ef22b4b",
      "filename": "app.js"
    },
    "update": {
      "version": "453a4c036a0897153bde04418ddfb200c3a12693",
      "filename": "update.js"
    }
  },
  "load": [
    "cordova-app-loader-complete.js",
    "autoupdate.js",
    "app.js",
    "update.js"
  ],
  "version": "3ff9e195602b971d60dfb4ad679f2cfac083c86e"
}
```
update.js
```
document.querySelector('.debug').innerHTML = 'updated 014';
```

**Comment by IqraRastee** [comment]
I am also having same error on android device. Any idea how to resolve it?

**Comment by betorobson** [comment]
could you paste your code here like I did before?

**Comment by IqraRastee** [comment]
Manifest file
```
{
  "files": { 
    "cordova-app-loader-complete": {
      "version": "76f1eecd3887e69d7b08c60be4f14f90069ca8b8",
      "filename": "js/cordova-app-loader-complete.js"
    },
    "autoupdate": {
      "version": "76f1eecd3887e69d7b08c60be4f14f90069ca8b8",
      "filename": "js/autoupdate.js"
    },
    "app": {
      "version": "8c99369a825644e68e21433d78ed8b396351cc7d",
      "filename": "js/application.js"
    },
    "index": {
      "version": "6e76f36f27bf29402a70c8adfee0f84b8a597815",
      "filename": "js/index.js"
    },
    "style": {
      "version": "6e76f36f27bf29402a70c8adfee0f84b8a595973",
      "filename": "css/application.css"
    }
  },
  "load": [
    "js/cordova-app-loader-complete.js",
    "js/autoupdate.js",
    "js/application.js",
    "js/index.js",
    "css/application.css"
  ]
}
```
index.html

```
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8" />
        <meta name="format-detection" content="telephone=no" />
        <meta name="msapplication-tap-highlight" content="no" />
        <meta http-equiv="Content-Security-Policy" content="default-src *; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval'">

        <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width, height=device-height" />
        
        
        <title>App</title>
    </head>
    <body>
        <div class="app">
            <div id="deviceready" class="blink">
                <p class="event listening">Connecting to Device</p>
                <p class="event received">Device is Ready</p>
            </div>
        </div>
        <script type="text/javascript" src="cordova.js"></script>
        <script type="text/javascript" 
            timeout="5100" 
            server="http://192.168.1.22:3000/assets/cordova/app/" 
            manifest="manifest.json" 
            src="js/bootstrap.js"></script>
    </body>
</html>

```

I update index.js from 
```
 onDeviceReady: function () {
    document.addEventListener("resume", app.onResume, false);
    document.addEventListener("pause", app.onPause, false);
    document.addEventListener("online", app.online, false);
    document.addEventListener("offline", app.offline, false);
    
    mobile_notification.registerDevice(function(result){});

    //Try to fire the app
    app.fireApp();
  }
```
to 
```
 onDeviceReady: function () {
    document.addEventListener("resume", app.onResume, false);
    document.addEventListener("pause", app.onPause, false);
    document.addEventListener("online", app.online, false);
    document.addEventListener("offline", app.offline, false);
    
    mobile_notification.registerDevice(function(result){});

    //Try to fire the app
    app.fireApp();
console.log("App fired");
  }
```
and update version of index.js in manifest.json
but I have not been able to get the updated file even once.
I also found out that the private flag _updateReady is never set.

**Comment by pheinicke** [comment]
Hi IqraRastee!

Have a look at https://github.com/markmarijnissen/cordova-app-loader/issues/41#issuecomment-119062511, the important part being:

> I realised that the cordova-app-loader-complete.js cannot be in the manigest file, so I put it after cordova.js and before de bootstrap.js. That's make it works.

**Comment by IqraRastee** [comment]
Hi pheinicke 
I removed the codova-app-loader-complete from manifest.json and added to index.html after cordova.js and before bootstrap.js but the result is same. :(

**Comment by betorobson** [comment]
Change the localRoot on object CordovaAppLoader inside autoupdate.js file to other name like "appv1". After that, rebuild your app e remote files.

I believe that you are facing a problem/bug during the whole process of debug and builds. My suggestion before your app be ok, delete the folder inside your device named same of localRoot of autoupdate.js.

**Comment by IqraRastee** [comment]
Thanks betorobson
I finally figured out that the issue was with the security policy. I needed to add cdvfile directive to it. 
I was unable to identify it because the error log would come and go very fast until I preserved the logs.

**Comment by betorobson** [comment]
Yeaahhhhh for sure!
It is exactly the same problem that I had here.

Cheers!
