### ISSUE TITLE
Getting status 404 while checking for update on the demo

### ISSUE THREAD

**Issue by murlex** [markmarijnissen/cordova-app-loader#45]
Hi!
I running Demo on Android platform (Genymotion emulator) and getting this response when clicking Check.
https://drive.google.com/file/d/0BzGAOVs2hi79TTBSN0tqSHpaclU/view?usp=sharing
Any idea, what could be a problem?
Thanx!

**Comment by murlex** [comment]
Tried on the real device. Still no luck, but the response is just empty JSON
{}

**Comment by murlex** [comment]
The same effect with my own web server (put on IIS7). I definitely missing some point here. Please, help.

**Comment by arieljake** [comment]
Are you expecting that url to work?

**Comment by arieljake** [comment]
Can you show it working in the browser directly?

**Comment by murlex** [comment]
Yes, the Demo working perfectly from Chrome. That what I've tried first. Then I followed the instructions for running on my own computer:

>git clone git@github.com:markmarijnissen/cordova-app-loader.git
>cd cordova-app-loader
>cordova platform add ios@3.7.0
>cordova plugin add org.apache.cordova.file
>cordova plugin add org.apache.cordova.file-transfer
>cordova run ios
For except that my platform is android instead of ios.

**Comment by murlex** [comment]
Oops! Sorry - please forget what I've said about timeout. It returns immediately with 404. I just clicked Check without previously click on Original or Update or so on... (with empty URL). So, what's the problem... scratching my head...

**Comment by murlex** [comment]
I am sorry for being so chatty, but this issue is really important to me...
Here what I've found:
http://docs.ionic.io/v1.0/docs/cordova-whitelist
Could it be relevant? My Cordova is 5.0.0.

**Comment by junmin-zhu** [comment]
You need run "cordova plugin add cordova-plugin-whitelist" before cordova build.

**Comment by ExecutorBG** [comment]
@junmin-zhu 
Thank you very much!

This should be added in the instructions.

**Comment by murlex** [comment]
Yes, I've already got that. Beat head against the wall for couple hours :) Unfortunately this is still not enough. Check & Download are ok with whitelist, but Update is not. I believe, because whitelist need some config. JS console complains about 404 for each file the manifest tries to load. I believe, the problem comes from CORS side because bootstrap.js loading the files from came from file:///android_asset/www while it tries to load scripts from cdvfile://localhost/persistent/app. Am I right?

**Comment by murlex** [comment]
Something? Anyone?

**Comment by murlex** [comment]
Oh.... finally I've got it all working with help of configuring whitelist.
I believe, someone guys. have to add all these things into installation document. Meaning, cordova plugin add whitelist and configuring it right with CSP adding cdfvile://* etc.).
Great plugin anyway, yet too much time spent to make it working for dummy like me :)

**Comment by micky2be** [comment]
Shall we close the issue then?

**Comment by murlex** [comment]
Yes, I believe. Yet it would be great for someone to take care to update .MD file...

**Comment by ObjectiveTruth** [comment]
Closing the issue since it appears to have been answered adequately, if there's more information to add to the discussion please reopen :ok_hand:
