### ISSUE TITLE
Security concerns

### ISSUE THREAD

**Issue by chilimix** [markmarijnissen/cordova-app-loader#47]
What will it take to password protect  the server side? I'm thinking something as simple as checking the request for a HTTP Header.

**Comment by micky2be** [comment]
Basic Auth, HTTPS, session management,... pick one.
Not sure this question is related to this repo though.

**Comment by ObjectiveTruth** [comment]
Closing because the questions seems to have been answered and may be out of scope of the project's goals. If the issue is still relevant please reopen :ok_hand:
