### ISSUE TITLE
relative image paths are broken after updating CSS in Android

### ISSUE THREAD

**Issue by yossi-shasho** [markmarijnissen/cordova-app-loader#48]
in my CSS, i use relative paths to background images e.g. `../img/image.gif`.
When the app autoupdates in iOS, the relative paths continue to work just fine.
However in android they're all broken links.

here are my loader settings:
```
loader = new CordovaAppLoader({
  fs: fs,
  localRoot: "www",
  serverRoot: serverRoot,
  mode: "mirror",
  cacheBuster: true,
  checkTimeout: 10000
});
```

and manifest:
```
{
  "files": {
    "app": {
      "version": "d548722725de794f8fd09a0e6857a7a353050aaa",
      "filename": "js/application.js"
    },
    "templates": {
      "version": "e7ded3afbf0b5b5d41c7dba2f052397283c6a8ca",
      "filename": "js/templates.js"
    },
    "style": {
      "version": "2da2c832c55f8c4aeb650d7103c62b77bb097e19",
      "filename": "css/ionic.app.css"
    }
  },
  "load": [
    "js/application.js",
    "js/templates.js",
    "css/ionic.app.css"
  ],
  "version": "33fe7fbd76074e53fced5d26bcbb4eb0f099003a"
}
```

Any idea? and why would it work differently in android?

**Comment by micky2be** [comment]
Sorry I'm a bit late to answer but can you use the cordova file protocol in your css?
It would look like this: `cdvfile://localhost/persistent/www/img/image.gif`

**Comment by ObjectiveTruth** [comment]
In my experience Android doesn't allow relative links in general of the form `../`, you have to make it relative to your www folder.

In your case I'd change your image links to `img/image.gif` instead of `../img/image.gif'

**Comment by ObjectiveTruth** [comment]
Closing since the issue seems to have been answered adequately, if there's more information to add to the discussion, please reopen :ok_hand:
