### ISSUE TITLE
Failed download still executes "then" function, not "catch"

### ISSUE THREAD

**Issue by dcartwright** [markmarijnissen/cordova-app-loader#53]
In testing, I had an app update download fail due to a configuration issue with my web server. The particulars aren't terribly important to this project, but essentially my manifest was listing a file that the server returns a 404 error for.

Now, when I debug into the code, I see that FileCache.download() is rejecting its promise. This is on line 506 of the "complete" app loader bundled file: https://github.com/markmarijnissen/cordova-app-loader/blob/master/dist/cordova-app-loader-complete.js#L506. That makes complete sense - after all the download _did_ fail. What then _doesn't_ make sense to me, and I think might be a bug, is that my `.then()` function still gets executed.

This is more or less the way my code is running the download/update (simplifying to keep things focused):
```
loader.download().then( function(manifest) {
    loader.update( true );
}).catch( function(error) {
    // show a message box saying the app update failed
});
```

When loader.update() is called, it checks `self._updateReady`, which of course is false, since the update is _not_ ready. So, the app is not actually updated, but my logic *thinks* it is. Moreover, my app is expecting `load.update( true );` to reload the page, so it doesn't show any messages to the user. Instead, my app just silently fails to update and sits there. The error handling "catch" function is never called.

So, it's not a _huge_ issue, but it took me a while to figure out what the heck was going on, because I had to debug all the way down into the library to see that the download was actually failing, and not some kind of weird "hang" when calling update().

**Comment by markmarijnissen** [comment]
good one! fixed in 1.1.0
