### ISSUE TITLE
How change destination folder instead of saving cache files on sdcard?

### ISSUE THREAD

**Issue by betorobson** [markmarijnissen/cordova-app-loader#57]
I'm looking for how to change it to not save download files from manifes.json on sdcard and save them on internal app folder. That would be great in case of download assets images which are showing up on Photos apps.

**Comment by ObjectiveTruth** [comment]
Not sure if this will help but, if you're just looking to not have it show up in photo apps, you can add an empty `.nomedia` file in the directory you want to have Android ignore it during media scans.

[Hide images and video from gallery](http://www.mindmytech.com/hide-whatsapp-images-videos-gallery/)

**Comment by betorobson** [comment]
Thank you buddy, that solved my issue :). I put it on my deploy tasks and also manifest generator.

**Comment by betorobson** [comment]
After a few days using this approach, I realised that It stops update remotely. So after a exhausting tests I could see the issue which is related to manifest json. The cordova-app-loader looks to it as a invalid file because it has a node named ".nomedia".

My solution was removed it from my manifest json and introduced a script on my app.js (cordova app script), its functions is write a .nomedia file on my cdvfile:// folder. This fixed my issues.

Conclusion, do NOT use ".nomedia" on manifest json instead write it manually.

**Comment by minhtc** [comment]
Hi @betorobson  Can you share the script that write a .nomedia file on cdvfile:// folder ?

**Comment by betorobson** [comment]
Hi @minhtc. Yes I can do that. Here you go.
```javascript
	writeNoMediaFile = function(){
		if(device.platform == 'Android'){
			console.log(cordova.file.externalRootDirectory);

			window.resolveLocalFileSystemURL(
				cordova.file.externalRootDirectory,
				function(dir){
					dir.getFile(
						'queromaissaude' + (window.DEVELOPMENT ? 'dev' : '') + '/.nomedia',
						{create:true},
						function(file) {
							console.log('got the file', file);
						}
					);
				}
			);
		}
	}
```

**Comment by minhtc** [comment]
Thank you. I've just found it in your project :) :
https://github.com/betorobson/cordova-remote-update/blob/master/mobileApp/src/js/app.js
