### ISSUE TITLE
Apply update for each user independantly

### ISSUE THREAD

**Issue by rammere** [markmarijnissen/cordova-app-loader#58]
Hey ,
Ur plugin is really great ... I wonder if there is away to upload diff code for each user .like if each user has his own id and we can update just for that user .
Regards,

**Comment by ObjectiveTruth** [comment]
This probably isn't helpful, but that sounds pretty involved. That definitely is not supported out of the box.

My suggestion would be to make a quick server that reads something in the header of the request and serves a different manifest/files based on that header parameter.

You can split your user's based on that header

Just a thought
