### ISSUE TITLE
FileCache.prototype.toPath file

### ISSUE THREAD

**Issue by Blewin** [markmarijnissen/cordova-app-loader#60]
Hey, I'm just wondering about this line in CordovaAppLoader.js:573
https://github.com/markmarijnissen/cordova-app-loader/blob/9e00159f16bf0f713a84afc57ced7cc4e71688dd/www/lib/CordovaAppLoader.js#L573
>	    url = url = this._fs.normalize(url || '');
>	    len = this.serverRoot.length;

1) len is not previously defined,
2) what is reason of double assignment of url?

**Comment by markmarijnissen** [comment]
Strange. Fixed it.
