### ISSUE TITLE
Write comparison section in README

### ISSUE THREAD

**Issue by ptarjan** [markmarijnissen/cordova-app-loader#61]
Can you compare and contrast why I want to use this project instead of what else is out there? I want to do live updates to my production app but I'm not sure which solution to pick. Just a cursory googling seems to leave me picking between:

* https://github.com/nordnet/cordova-hot-code-push
* https://github.com/markmarijnissen/cordova-app-loader
* http://docs.ionic.io/v1.0/docs/deploy-from-scratch

and I'm sure I missed some that you know about. You know the space much better than me, so seeing a comparison written by you would help a lot.

**Comment by markmarijnissen** [comment]
Hi!


Good idea! Unfortunately I havent been keeping up with all latest developments, as there are currently no paying customers that use this project (so I can only work in free time on this project).




I see what I can do - but can't promise much now





—
