### ISSUE TITLE
manifest.json question

### ISSUE THREAD

**Issue by JosephDAM** [markmarijnissen/cordova-app-loader#66]
Hi, this ain't really an issue, I just wanted to ask you about the manifest.json.
In "'files': {}" I have to write up all the files my app has? or just the ones you have?
where do I get the "version" from?
what files should I put in "'load': []"? I dont even have a 'style.css'

Thanks and sorry if my questions are kinda low tier

**Comment by ObjectiveTruth** [comment]
The files are all the files you want to have loaded by `cordova-app-loader`, the version is an md5 hash that can be computed using most cryptographic libraries. This hash is used to determine if the file on the server's `manifest.json` is different than the one in the device before downloading everything. There's a `grunt` script in the library you can use to automate this

There's a gulp task for making the manifest here:

https://github.com/ObjectiveTruth/gulp-cordova-app-loader-manifest

Disclamer: I made the gulp library

**Comment by JosephDAM** [comment]
- Project
  - www
    - public
      - css
      - img
      - js
        - angular
        - more modules...
        - app.js
    - src
      - login
        - css
        - img
        - js
      - functionality1
        - css
        - img
        - js
      - functionality2
        - css
        - img
        - js
      - body.html
      - structure.html
    - index.html

So this is my project structure, it has a lot of files, like 200+ (.js, .html, .css, .png, .json, etc), so if i'm not mistaken, at the same level as my index.html, I should have my manifest, this manifest should include all the files that should be checked at the beginning of each execution to see if they have a new version, so they can be uploaded. Thing is, I want all files to be checked, I even want to include files that weren't there before. Like a new javascript file in 'functionality2>js>controllers>modal>new.js', can I do this? Rigth now I was looking at the grunt file that I think you mean, https://gist.github.com/arieljake/19447838b29a3e2da92b, never used grunt, but seeing the docs and so, when I install grunt, will it generate a manifest.json with all my files when I execute this grunt file? But isn't the gulp library you made for the same purpose? 

While I'm writing this I'm checking again and againt a lot of docs. My conclusion: http://i.kinja-img.com/gawker-media/image/upload/japbcvpavbzau9dbuaxf.jpg

No but seriously, the only grunt file I see in cordova-app-loader is https://gist.github.com/arieljake/19447838b29a3e2da92b, and your gulp, both are to generate a manifest aren't they? If so, what grunt file did you mean? or you just telling me I can do it either way? And the load section, I still don't know what should be there, my index.html has like 18 'script' and 5 'link rel="stylesheet"', are these the ones I have to include in "load"?

Again I'm reading the docs, is it maybe that the grunt file only updates my server manifest changing the version, and the gulp generates the very first manifest?

And again, sorry for my ignorance driven questions, and thank you.

**Comment by JosephDAM** [comment]
Gonna use this thread for another question.
I don't quite get what I have to do with window.BOOTSTRAP_OK. 
Do I have to set it true when my app loads? for what purpose? Isn't the autoupdate.js the first thing that executes? do I have to set it true here?

**Comment by JosephDAM** [comment]
Another quetion:
On your docs, at Installation, step 2: Download and include bootstrap.js...
I already use bootstrap.min.css, does this make some kind of conflict? Last time I tried the app I lost the style of my button, it became a blue button...
I also use ui-bootstrap/ui-bootstrap-tpls-0.12.0.js, does this make some kind of conflict?
"Add bootstrap.js to your index.html.", so, should it look like this:
``` 
<script type="text/javascript" 
    server="http://192.160.80.50/MyApp/www" 
    manifest="manifest.json" 
    src="bootstrap.js"></script>
```
 or like this: 
```   
<script type="text/javascript" 
    timeout="5100" 
    manifest="manifest.json" 
    src="bootstrap.js"></script>
``` 
?
Then, in the manifest, should I write cordova.js in .load? or not? You don't have it... so with the one in index it's enough? Because I'm pretty sure cordova didn't load. (I couldn't use the android menu, I already had this problem and it was because someone commented the script tag with cordova.js, so with the cordova.js at manifest.load I dont have cordova in my app, or that is how it looks like)

This was installation, now lets go with usage.
Welp, appart from not knowing how the script tag should look like, I have this questions:
- Step 1: Bootstrap your app.

"On the second run, the manifest.json is retrieved from localStorage.

Set window.BOOTSTRAP_OK to true when your app has succesfully launched."
I don't quite get this, second run? Anyways, "Set window.BOOTSTRAP_OK to true" where? in the autoupdate.js? or in one of my files?

**Comment by markmarijnissen** [comment]
old issue, closing
