### ISSUE TITLE
Maybe a problem with headers

### ISSUE THREAD

**Issue by JosephDAM** [markmarijnissen/cordova-app-loader#67]
I'm getting this errors in the chrome console, this 3 messages repeat themselfs again and again.

>XMLHttpRequest cannot load http://myServerIp/MyProject/www/manifest.json. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost' is therefore not allowed access. (index):1 

>Uncaught SyntaxError: Unexpected end of input (index):1 
>>window.pegasus.xhr.onreadystatechange.xhr.then @ bootstrap.js:34

>Auto-update error: Error: new manifest timeout(…) autoupdate.js?1444116785423:43
>>(anonymous function)	@	VM258 autoupdate.js?1444116785423:43
>(anonymous function)	@	cordova-app-loader-complete.js?1444116785423:1166
>onNextTick	@	cordova-app-loader-complete.js?1444116785423:1354
>drainQueue	@	cordova-app-loader-complete.js?1444116785423:1391

And again, XMLHttpRequest, Uncaught SyntaxError, Auto-update error, and so on.
In the Chrome Developer Tools tab 'network' I can see how Request URL:http://myServerIp/MyProject/www/manifest.json keeps repeating, sometimes it gives a 'Status Code:200 OK (from cache)' and sometimes 'Status Code:304 Not Modified', in both cases the error that I wrote up there shows.

Greetings

**Comment by JosephDAM** [comment]
From the app I get this errors:
>ERROR	Web Console	Could not get Cordova FileSystem: at file:///android_asset/www/cordova-app-loader-complete.js?1444119402848:715
>WARN	Web Console	New manifest available, but an earlier update attempt failed. Will not download. at file:///android_asset/www/cordova-app-loader-complete.js?1444119402848:180

**Comment by markmarijnissen** [comment]
You did't configure CORS correctly at your server. Google can help you :)
