### ISSUE TITLE
Security concerns

### ISSUE THREAD

**Issue by pke** [markmarijnissen/cordova-app-loader#68]
Nice idea. However aren't there any security concerns with that "single source of truth"? How do you prevent a malicious version of the app to be deployed to the users? Couldn't somebody intercept calls to the update server and change the content delivered to the client?

How about some code signing and signature verification?

**Comment by betorobson** [comment]
I believe that any critical part of your app should not be remote updated. This feature its awesome to update assets e some parts that not affect any logical struct.

**Comment by albinekb** [comment]
Use SSL (https)?

**Comment by markmarijnissen** [comment]
Best idea:
- md5-hash all files
- verify md5-hash of all files on download
- create a version hash: use some asymmetric encryption algorithm to sign all file-hashes on the server
- verify integrity by checking the version hash.

A weaker, but easer idea would be to have a shared secret. Only this depends on the smartphone javascript files or browser being hackable.
