### ISSUE TITLE
FileTransferError 404 ios

### ISSUE THREAD

**Issue by hama2015** [markmarijnissen/cordova-app-loader#71]
File Transfer Finished with response code 404
2015-12-02 11:12:31.064 peak_mobile[6520:1536503] FileTransferError {
    body = "";
    code = 1;
    "http_status" = 404;
    source = "cdvfile://localhost/bundle/www/views/views/app.js";
    target = "cdvfile://localhost/persistent/app/views/app.js";
}

**Comment by betorobson** [comment]
Hi, you might be having an issue to point out your remote files. Have a like in these instructions which I made. https://github.com/betorobson/cordova-remote-update
