### ISSUE TITLE
how to update/download new added files?

### ISSUE THREAD

**Issue by wliyongfeng** [markmarijnissen/cordova-app-loader#73]
I read #63, and it seems we can load new added files. I tried, but failed.

Could someone give some detail about this?

I use angularjs to build my app and I will add new html files when new features introduced. If my previous `manifest.json` is as follows:

```
{
  "files": {
    "foo.html": {
      "filename": "templates/foo.html",
      "version": "347c1f164f0ba02f18374d881c1a89ef6b674107f231e7986ab12c4af12d7034"
    }
  },
  "load": [
    "templates/foo.html"
  ],
  "root": "./"
}
```

How can I add new file for example `bar.html`? Does the following `manifest.json` work?

```
{
  "files": {
    "foo.html": {
      "filename": "templates/foo.html",
      "version": "347c1f164f0ba02f18374d881c1a89ef6b674107f231e7986ab12c4af12d7034"
    },
    "bar.html": {
      "filename": "templates/foo.html",
      "version": "4e248949f7c3fbcfc8f941fff8fffdc22516686c54b1be411ea43d41a2a08ff9"
    }
  },
  "load": [
    "templates/foo.html",
    "templates/bar.html"
  ],
  "root": "./"
}
```

**Comment by zhoumin4228343** [comment]
i have same problems as yours , do you get a solution?

**Comment by wliyongfeng** [comment]
@zhoumin4228343  No, I gave up using `cordova app loader`.

**Comment by betorobson** [comment]
I believe these questions goes forward. For me does not make sense update a html file, instead of it I suggest a SPA for mobile apps and put everything together in a singles JS file.

**Comment by markmarijnissen** [comment]
It makes no sense - how do you load a "html" file?

Mobile browsers don't support the modern html import function yet. So you have to write custom JS to load HTML.

Therefore, the Manifest.load should not load it, but your application javascript.

Or... just bundle it with your JS instead.
