### ISSUE TITLE
android can not updata

### ISSUE THREAD

**Issue by jy03078959** [markmarijnissen/cordova-app-loader#75]
cordova-app-loader is run success on ios and chrome,but android was fail. on android .check is ok,download is ok.but reload not ok. this is old ,not new

**Comment by ldrvoderic** [comment]
Try to add to your config.xml
<access origin="cdvfile:*"/>
<allow-navigation href="cdvfile:*"/>
<allow-intent href="cdvfile:*"/>

**Comment by pengkobe** [comment]
@ldrvoderic thank you very much. you solution works fine for me!
