### ISSUE TITLE
How to handle duplicate filenames in manifest.json

### ISSUE THREAD

**Issue by andrewpnlp** [markmarijnissen/cordova-app-loader#78]
Hi,
Stupid question - how should duplicate filenames be handled.

For example, if I have two files below, what key should be used for the second one instead of "bootstrap" again? If I've read the code correctly, using the same key will corrupt the manifest parsing?

Regards,
Andy

```
{
  "files": {  // these files are downloaded 
    "bootstrap": {
      "version": "76f1eecd3887e69d7b08c60be4f14f90069ca8b8",
      "filename": "bootstrap.js"
    },
    "XXXXX": {
      "version": "76f1eecd3887e69d7b08c60be4f14f90069ca8b8",
      "filename": "lib/bootstrap.js"
    },.....
```

**Comment by betorobson** [comment]
Like this:
`
{
  "files": {  // these files are downloaded 
    "bootstrap": {
      "version": "76f1eecd3887e69d7b08c60be4f14f90069ca8b8",
      "filename": "bootstrap.js"
    },
    "lib_bootstrap.js": {
      "version": "76f1eecd3887e69d7b08c60be4f14f90069ca8b8",
      "filename": "lib/bootstrap.js"
    },.....
`

**Comment by markmarijnissen** [comment]
indeed!
