### ISSUE TITLE
BUNDLE_ROOT location on iOS, using Phonegap

### ISSUE THREAD

**Issue by gRegorLove** [markmarijnissen/cordova-app-loader#86]
I've been having difficulty using this with Phonegap to copy my app files. To debug, I tried a simple app that calls FileTransfer directly to copy a bundled file to the dataDirectory. I'm still getting a 404.

I copied [these lines](https://github.com/markmarijnissen/cordova-app-loader/blob/master/www/lib/CordovaAppLoader.js#L52) to set the BUNDLE_ROOT and then tried to download an image from the BUNDLE_ROOT to `cordova.file.dataDirectory`. That's when I get a 404. I added some code to loop through directories and list the files in them; none of my app's image assets appear to be in BUNDLE_ROOT.

I'm using Phonegap 5.4.1 and their Phonegap Developer app to test locally on my devices without needing to build first. It appears on iOS the bundled files are actually in `cdvfile://localhost/library-nosync/phonegapdevapp/www/` and not `cdvfile://localhost/bundle/`, which the above code uses.

Is this a discrepency between Cordova and Phonegap Developer with regard to filesystem locations, or does the cdvfile URL in the above code need to be changed? Thanks for any assistance.

**Comment by gRegorLove** [comment]
@markmarijnissen? Anyone?

**Comment by markmarijnissen** [comment]
this is fixed now!
