### ISSUE TITLE
Update doesn't work with files in subdirectories

### ISSUE THREAD

**Issue by mparpaillon** [markmarijnissen/cordova-app-loader#90]
[May solve #87 and #75]

Hi @markmarijnissen !

I've worked all day on your plugins (app-loader, file-cache and promise-fs) and they're great !

I've spent several hours trying to find out why the update didn't work on my Android device.
Apparently it's because the file I'm trying to update is in a subdirectory => `/js/main.min.js`

I think your example works fine because you don't have any synchronized file in subdirectories.

Apparently there is an issue in cordova-promise-fs `list` function. It looks like the `Promise.all()` (https://github.com/markmarijnissen/cordova-promise-fs/blob/master/index.js#L240) is resolved before the subdirectories are read.

So I've added lots of debug and I get this

![capture d ecran 2016-03-27 00 25 18](https://cloud.githubusercontent.com/assets/1062115/14062938/6e51968a-f3b2-11e5-9ccc-17184d593e2e.png)

As you can see, I go back in the `FileCache` `list` function too soon... so the list of entries is empty... so nothing is in cache... so `isDirty()` returns true.... so `loader.update();` returns false.

I tried to fix this but I didn't succeed. Hope you can help me

Thanks a lot

**Comment by mparpaillon** [comment]
I can confirm that everything works fine when I try the same scenario but with my js file __not__ in a subdirectory

**Comment by domharrington** [comment]
I'm having the same issue as this. Thanks for your detailed of the problem... gunna try and investigate further now. Weirdly it was all working for me earlier on today, but now i can't get an update to ever successfully apply because of that `self.isDirty()` call always returning true.

**Comment by domharrington** [comment]
Think this is related to https://github.com/markmarijnissen/cordova-promise-fs/pull/15#issuecomment-216926505

**Comment by mparpaillon** [comment]
Yep looks like it !
Thanks for looking into it

**Comment by domharrington** [comment]
Did you come up with an alternative solution? Or use another library?

**Comment by mparpaillon** [comment]
I haven't work on it since last time. Anyway I tried to fix the promise supposed to list the items recursively but I couldn't :s

**Comment by markmarijnissen** [comment]
should be fixed now, please reopen is issue still persists.

**Comment by domharrington** [comment]
Working well for me now. Thanks for your speedy responses and fix for the issue.

**Comment by domharrington** [comment]
@markmarijnissen there appears to be a problem in the latest release. On a successful update only the files that have been updated and are now present in the cache are available. E.g. i've updated www/js/build/app.js and not app.css, then on update only the JS file is available. If i then update the css file and re-update, then it is available.

Has there been a change introduced which would now not store all existing files as well as the files that have been updated?

**Comment by domharrington** [comment]
It appears as though this line here is causing the issue: https://github.com/markmarijnissen/cordova-app-loader/commit/c33e7937ae911bbafec5ee18c7ab7dee016058ff#diff-168726dbe96b3ce427e7fedce31bb0bcL156.

Line changed from:
```js
- oldFiles[file].version !== newFiles[file].version ||
```
To:
```js
+ oldFiles[file].version !== newFiles[file].version //||
```

Was this accidental?
