### ISSUE TITLE
Download onprogress undefined variable

### ISSUE THREAD

**Issue by yoandinkov** [markmarijnissen/cordova-app-loader#91]
When using `onprogress `callback of self.download() an error occurs:
`Uncaught (in promise) ReferenceError: index is not defined`. There is uninitialised variable on line 477 in cordova-app-loader-complete.js 
`if(ev.loaded > 0 && ev.total > 0 && index!== total){` - index is not defined

**Comment by mishoboss** [comment]
Same here while trying to reproduce the sample in Cordova

**Comment by domharrington** [comment]
Getting a similar error as the above but not during the `onprogress` callback. The error appears to be coming from cordova.js:312 at the end of a try...catch block:

```
catch (err) {
    var msg = "Error in " + (isSuccess ? "Success" : "Error") + " callbackId: " + callbackId + " : " + err;
    console && console.log && console.log(msg);
    cordova.fireWindowEvent("cordovacallbackerror", { 'message': msg });
    throw err;
}
```

Errors look like the following:
```
Error in Success callbackId: FileTransfer1241210121 : ReferenceError: index is not defined
cordova.js:312 Uncaught ReferenceError: index is not defined
```

I have the following module versions:

```
cordova@6.1.1
cordova-app-loader@0.18.0
cordova-promise-fs@1.0.1
cordova-plugin-file@4.2.0
cordova-plugin-file-transfer@1.5.1
```
