### ISSUE TITLE
Complicated nested dependencies?

### ISSUE THREAD

**Issue by domharrington** [markmarijnissen/cordova-app-loader#94]
To install this package, you need to have the following dependency tree:

```
- cordova-app-loader
  - cordova-promise-fs
  - cordova-file-cache
    - cordova-promise-fs
- cordova-promise-fs
```

Is there any way we can simplify this dependency structure? Maybe so that you don't need to create a new instance of `cordova-promise-fs` when creating a `cordova-app-loader` instance. I get that it is so that you can override the `Promise` implementation but maybe the `Promise` library can be provided as an argument to the constructor.

So from https://github.com/markmarijnissen/cordova-app-loader#step-2-intialize-cordovaapploader:

```js
var CordovaPromiseFS = require('cordova-promise-fs');
var CordovaAppLoader = require('cordova-app-loader');
var Promise = require('bluebird');

var fs = new CordovaPromiseFS({
  Promise: Promise
});

var loader = new CordovaAppLoader({
  fs: fs,
  serverRoot: 'http://data.madebymark.nl/cordova-app-loader/',
  localRoot: 'app',
  cacheBuster: true, // make sure we're not downloading cached files.
  checkTimeout: 10000 // timeout for the "check" function - when you loose internet connection
});
```

To this:
```js
var CordovaAppLoader = require('cordova-app-loader');
var Promise = require('bluebird');

var loader = new CordovaAppLoader({
  Promise: Promise
  serverRoot: 'http://data.madebymark.nl/cordova-app-loader/',
  localRoot: 'app',
  cacheBuster: true, // make sure we're not downloading cached files.
  checkTimeout: 10000 // timeout for the "check" function - when you loose internet connection
});
```

That way if any bugs are found in `cordova-promise-fs` the updates need to happen in less places.

**Comment by domharrington** [comment]
As far as I can see, the only place the `fs` option to `cordova-app-loader` is used is [here](https://github.com/markmarijnissen/cordova-app-loader/blob/7c47e8a948675b9ab45a5a989d61a01bd7617f36/index.js#L30) to fetch the Promise implementation used. This means that it can be safely switched out with minimal code changes.

**Comment by domharrington** [comment]
On further inspection, it looks as though it is passed down to https://github.com/markmarijnissen/cordova-file-cache [here](https://github.com/markmarijnissen/cordova-app-loader/blob/7c47e8a948675b9ab45a5a989d61a01bd7617f36/index.js#L45) which leads through to [here](https://github.com/markmarijnissen/cordova-file-cache/blob/4a2a741671817cdc76d2c3dbf961540ca87a1540/index.js#L9). 

In that case, maybe the `cordova-promise-fs` dependency isn't required at all in `cordova-app-loader`?

**Comment by markmarijnissen** [comment]
Yes, the idea is to share a single FS instance for multiple uses (i.e. a File Cache, the App Loader, or manual operations).

As you manually pass the FS instance, I could simply remove the "cordova-promise-fs" dependency.
