### ISSUE TITLE
_createFilemap fails on iOS

### ISSUE THREAD

**Issue by yoandinkov** [markmarijnissen/cordova-app-loader#98]
That's a tricky one, I think, but I have following scenario on iOS (i have tested on most devices with version 8 and 9). When trying to download new files **this.manifest** which have been loaded from _window.Manifest _ is plain object and don't have property **files**. So during the process when we get in `_createFilemap` `Object.keys()` is executed with undefined - which fails silently and download never continues . I suspect that pegasus request to local manifest.json haven't completed by the time the **this.manifest** is being initialized. So it stays with plain object. I'm patching the issue by adding empty **files** property by the time we are initializing variables. I'm using cordova-app-loader-complete.js

```
 // initialize variables
 this.manifest = window.Manifest;
 this.manifest.files = window.Manifest.files || {};
 this.newManifest = null;
 this.bundledManifest = null;
 this.preventAutoUpdateLoop = options.preventAutoUpdateLoop === true;
 this._lastUpdateFiles = localStorage.getItem('last_update_files');
```

**Comment by markmarijnissen** [comment]
wow, hard one. thanks for investigating. 
will be fixed in next release.

**Comment by yoandinkov** [comment]
When do you plan to do a next release?

**Comment by markmarijnissen** [comment]
It is done :) 1.2.0

Op do 12 mei 2016 10:52 schreef Yoan Dinkov <notifications@github.com>:
