### ISSUE TITLE
Cache busting for manifest.json

### ISSUE THREAD

**Issue by SystemParadox** [markmarijnissen/cordova-app-loader#99]
It seems there is no cache busting for manifest.json. It's taken me hours to work out why my app wasn't getting updates.

Is there any reason why we cannot apply cache busting to manifest.json?

Even if we can't do that, it would be nice to add a warning to the readme that we must make absolutely sure that the server issues the right cache-control headers so that the manifest.json is never ever allowed to be cached.

**Comment by markmarijnissen** [comment]
There is no reason. So I've added it in the next release!

**Comment by SystemParadox** [comment]
Excellent! Thanks very much.
